### ISSUE TITLE
20.10: Fractional scaling switch not present

### ISSUE THREAD

**Issue by leviport** [pop-os/mutter#11]
It appears the fractional scaling switch is not enabled in Groovy yet. I tested both with https://github.com/pop-os/gnome-control-center/pull/122 added and without.

![groovy-no-frac](https://user-images.githubusercontent.com/13512097/96520219-d583a400-122b-11eb-803b-dcbcbd3375ff.png)

**Comment by ids1024** [comment]
Should be resolved now that https://github.com/pop-os/mutter/pull/12 and https://github.com/pop-os/gnome-control-center/pull/124 are merged.
