### ISSUE TITLE
mutter does not support different workspaces per monitor

### ISSUE THREAD

**Issue by jasonriedy** [pop-os/mutter#18]
Upstream: https://gitlab.gnome.org/GNOME/mutter/-/issues/37

Just an FYI.  About to jump to sway for this use as an i3 user on X.  I'd rather not have to build my own DE, but I don't have a choice for my workflow (laptop: communication / debugging, main screen: editing, side screen: documentation / visualization).  It's sad that mutter and the rest are so confused about multiple monitors.

**Comment by jacobgkau** [comment]
This is also being tracked in the Pop Shell repo: https://github.com/pop-os/shell/issues/823

**Comment by jasonriedy** [comment]
Sorry, forgot I filed that.  To many different bug repos.
