### ISSUE TITLE
Remote Desktop for Wayland?

### ISSUE THREAD

**Issue by lfom** [pop-os/mutter#9]
Hello. First of all, thanks a lot for all the work to build and maintain Pop!_OS, it is a great OS and I hope it keeps improving for years to come.
I didn't know Pop uses a custom Mutter build, so maybe it is related. Recently I tried to activate the built-in remote desktop service while running Wayland, but it looked like it was not enabled (RD on Wayland uses PipeWire, while on XOrg it uses `vino`).This documentation is old, but it may help to make what I mean clear:
https://wiki.gnome.org/Projects/Mutter/RemoteDesktop
Is it disable on Pop!_OS? Any chances it will be enabled in the future?
Regards

**Comment by ids1024** [comment]
Wayland isn't really officially supported on Pop!_OS, but https://github.com/pop-os/mutter/pull/13 will probably make remote desktop with Wayland work (on Pop!_OS 20.10). Though I've only tried it on X.

**Comment by ids1024** [comment]
Closing since this should be working in Pop!_OS 20.10 as stated above.

**Comment by nekdolan** [comment]
@ids1024 RDP has never worked for me in 20.10 wayland

![vnc](https://user-images.githubusercontent.com/715213/116788314-33315c80-aaa9-11eb-8ca7-095a622d106f.png)

**Comment by lfom** [comment]
It works on 20.10, until the screen locks. There is a command you can enter in the Looking Glass to disable this Gnome Shell behavior tho.

**Comment by nekdolan** [comment]
@lfom for me I might see part of the screen for half a second and then black screen. (RealVNC)

In UltraVNC I can connect and display the top left quarter of the screen and I can even move the mouse, but that is all. I think mutter is not setting the correct screen resolution for the stream.

**Comment by lfom** [comment]
@nekdolan I think I have used Remmina and maybe NoMachine when I tested (Wayland, of course, no nVidia).
